spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://101.34.64.122:3306/site?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: e3d5%f7Dv*6w
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver